runtime: go
api_version: go1

handlers:

# The root URL (/) is handled by the Go application.
# No other URLs match this pattern.
- url: /
  script: _go_app

# A regular expression indicating that it should be handled
# by the Go application.
- url: /hello
  script: _go_app

# All other URLs are handled by the Go application.
- url: /.*
  script: _go_app